# Development management access and project topology permissions at initialization.
default_user_tags.management = true
default_permissions.configure = ^relay[.].*
default_permissions.write = ^relay[.].*
default_permissions.read = ^relay[.].*
